import { StyleSheet } from 'react-native';

const styles = StyleSheet.create({
  container: {
    paddingStart: 14,
    paddingEnd: 14,
  },
  title: {
    marginTop: 8,
    color: '#FFF',
    fontSize: '1.1rem',
    textAlign: 'center',
  },
  pricesHeader: {
    flex: 1,
    flexDirection: 'row',
    marginTop: 14,
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  pricesHeaderRow: {
    backgroundColor: '#D6D585',
    width: '20%',
    height: 'auto',
    textAlign: 'center',
    color: '#000',
    fontWeight: 'bold',
    fontSize: '1rem',
    paddingTop: 12,
    paddingBottom: 12,
    paddingRight: 8,
    paddingLeft: 8,
    borderRadius: 8,
  },
  pricesHeaderRowProduto: {
    backgroundColor: '#D6D585',
    width: '34%',
    height: 'auto',
    textAlign: 'center',
    color: '#000',
    fontWeight: 'bold',
    fontSize: '1rem',
    paddingTop: 12,
    paddingBottom: 12,
    paddingRight: 8,
    paddingLeft: 8,
    borderRadius: 8,
  },
  priceRowContainer: {
    flex: 1,
    flexDirection: 'row',
    marginTop: 8,
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  priceRow: {
    backgroundColor: '#282829',
    width: '20%',
    height: 'auto',
    textAlign: 'center',
    color: '#FFF',
    fontWeight: 'bold',
    fontSize: '1rem',
    paddingTop: 12,
    paddingBottom: 12,
    paddingRight: 8,
    paddingLeft: 8,
    borderRadius: 8,
  },
});

export default styles;
