import { StyleSheet } from 'react-native';

const styles = StyleSheet.create({
  container: {
    marginStart: 14,
    marginEnd: 14,
  },
  title: {
    marginTop: 8,
    color: '#FFF',
    fontSize: '1.1rem',
    textAlign: 'center',
  },
  info: {
    flex: 1,
    marginTop: 12,
    flexDirection: 'row',
    justifyContent: 'space-between',
    gap: 4,
  },
  infoInput: {
    backgroundColor: '#282829',
    textAlign: 'center',
    color: '#FFF',
    fontWeight: 'bold',
    fontSize: '1rem',
    paddingTop: 12,
    paddingBottom: 12,
    borderRadius: 8,
  },
  dateInput: {
    width: '40%',
    height: 'auto',
  },
  establishmentInput: {
    width: '55%',
    height: 'auto',
  },
  pricesHeader: {
    flex: 1,
    flexDirection: 'row',
    marginTop: 14,
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  pricesHeaderRow: {
    backgroundColor: '#D6D585',
    width: '20%',
    height: 'auto',
    textAlign: 'center',
    color: '#000',
    fontWeight: 'bold',
    fontSize: '1rem',
    paddingTop: 12,
    paddingBottom: 12,
    paddingRight: 8,
    paddingLeft: 8,
    borderRadius: 8,
  },
  pricesHeaderRowEditable: {
    color: 'rgb(49 53 203)',
  },
  pricesHeaderRowProduto: {
    backgroundColor: '#D6D585',
    width: '34%',
    height: 'auto',
    textAlign: 'center',
    color: '#000',
    fontWeight: 'bold',
    fontSize: '1rem',
    paddingTop: 12,
    paddingBottom: 12,
    paddingRight: 8,
    paddingLeft: 8,
    borderRadius: 8,
  },
  priceRowContainer: {
    flex: 1,
    flexDirection: 'row',
    marginTop: 8,
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  priceRow: {
    backgroundColor: '#282829',
    width: '20%',
    height: 'auto',
    textAlign: 'center',
    color: '#FFF',
    fontWeight: 'bold',
    fontSize: '1rem',
    paddingTop: 12,
    paddingBottom: 12,
    paddingRight: 8,
    paddingLeft: 8,
    borderRadius: 8,
  },
  buttonContainer: {
    marginTop: 12,
    marginBottom: 12,
    flex: 1,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 8,
  },
  button: {
    marginTop: 10,
    paddingRight: 15,
    paddingLeft: 15,
    paddingTop: 8,
    paddingBottom: 8,
    borderRadius: 8,
    backgroundColor: '#D6D585',
    alignSelf: 'center',
  },
  buttonIcon: {
    fontWeight: '700',
  },
});

export default styles;
